### ISSUE TITLE
clamdscan : quick scan with daemon

### ISSUE THREAD

**Issue by AlrikRr** [USBGuardian/USBGuardian#2]
Hello, Bonjour,

I just made a few test with USBGuardian (that's an amazing project btw) and the scan time for a 15Gb USB was too long (8 minutes for 2 file (14Ko)) I realize that issue was due to "clamscan" command. Unfortunately, this command will charge all the signatures before the scan. On a good PC the scan is about one minute but on a Raspebrry Pi B that's really bad.
After a few documentation about clamav I found the clamdscan command. This command will init a daemon and charge all the signature before the scan. On a raspberry pi B, the normal scan was 8 minutes and the daemon scan was 10 secondes !

A made a few test and it's working well. I just have a few issues with the daemon, sometimes nothing is working. I was able to integrate clamdscan into scan.py, when the daemon is not doing anything it works fine. However, I have a problem with the scanAndRemove.py, the scan does not delete the files and the formatting does not work.

**Comment by USBGuardian** [comment]
Hello @RedFou52, 
Unfortunately, the project is no longer being maintained. Performance does really depends on the device used. This project was mainly a proof of concept since we hadn't a lot of time to work on it,   but feel free to improve it. Open a pull request  with the improvement, I'll review it to merge it 😄
Don't hesitate to ping me, if you struggle too much with the code, i will dig into it even if it was done while ago !

**Comment by AlrikRr** [comment]
Thank you for your reply ! I'll try to improve it then :)
